### ISSUE TITLE
Unable to apply after clicking Easy Apply

### ISSUE THREAD

**Issue by rahul-lohra** [feder-cr/Auto_Jobs_Applier_AIHawk#313]
Please check the video https://mixdrop.is/f/034x8ml3uk0oqo

![image](https://github.com/user-attachments/assets/c83d4994-3048-45bf-a9cf-b9bde26d5b39)
![image](https://github.com/user-attachments/assets/7a084f4a-d356-4c24-9435-1889c35fe3f4)

**Comment by OrestisIon** [comment]
I have the same issue

**Comment by Moh4mad97** [comment]
Same here

**Comment by thomHayner** [comment]
I also ran into this issue yesterday while trying to test a PR that relates to specific jobs.

I only changed the parts of my resume that I thought  I would need for testing that PR, then I tried to test it and had this same error.
My initial though was that the bot is deciding that overall I am not a good fit for the job based on my resume, and it was doing a delayed exit from the application.

I did not have time yet to make a completely new application and retry to see if that was the issue.
This was just one possibility, but I am seeing now that others are having the same issue.

Are you sure that your resume is a good fit for the roles where the applications are being discarded?
Do you meet the educational requirements for the position?
Do you have requisite experience for the job?

I am wondering if that may the issue...i.e. the bot is properly deciding that this is not an appropriate job and it is discarding the application, just not at the right time...

**Comment by thomHayner** [comment]
Same issue.

For me this bug gets to the "upload resume" step and that is when it quits...I have now tried it with three different resume styles, all fail.

Logs indicate that it is an upload issue with the resume format, possibly related to PR #349...complete logs of the error I receive are attached below:

```
Starting Chrome browser to log in to LinkedIn.
Navigating to the LinkedIn login page...
User is already logged in.
Starting the search for clearance jobs in United States.
Going to job page 0
Starting the application process for this page...
Traceback (most recent call last):
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 200, in _create_and_upload_resume
    f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/manager_facade.py", line 81, in pdf_base64
    pdf_base64 = HTML_to_PDF(temp_html_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 25, in HTML_to_PDF
    driver = create_driver_selenium()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 18, in create_driver_selenium
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__
    service.path = DriverFinder.get_path(service, options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
    raise err
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
    result = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
    raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug.
The chromedriver version cannot be discovered


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 61, in job_apply
    self._fill_application_form(job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 125, in _fill_application_form
    self.fill_up(job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 169, in fill_up
    self._process_form_element(element, job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 173, in _process_form_element
    self._handle_upload_fields(element, job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 190, in _handle_upload_fields
    self._create_and_upload_resume(element, job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 206, in _create_and_upload_resume
    raise Exception(f"Upload failed: \nTraceback:\n{tb_str}")
Exception: Upload failed: 
Traceback:
Traceback (most recent call last):
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 200, in _create_and_upload_resume
    f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/manager_facade.py", line 81, in pdf_base64
    pdf_base64 = HTML_to_PDF(temp_html_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 25, in HTML_to_PDF
    driver = create_driver_selenium()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 18, in create_driver_selenium
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__
    service.path = DriverFinder.get_path(service, options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
    raise err
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
    result = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
    raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug.
The chromedriver version cannot be discovered



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_job_manager.py", line 126, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 65, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception: 
Traceback:
Traceback (most recent call last):
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 200, in _create_and_upload_resume
    f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/manager_facade.py", line 81, in pdf_base64
    pdf_base64 = HTML_to_PDF(temp_html_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 25, in HTML_to_PDF
    driver = create_driver_selenium()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 18, in create_driver_selenium
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__
    service.path = DriverFinder.get_path(service, options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
    raise err
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
    result = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
    raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug.
The chromedriver version cannot be discovered


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 61, in job_apply
    self._fill_application_form(job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 125, in _fill_application_form
    self.fill_up(job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 169, in fill_up
    self._process_form_element(element, job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 173, in _process_form_element
    self._handle_upload_fields(element, job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 190, in _handle_upload_fields
    self._create_and_upload_resume(element, job)
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 206, in _create_and_upload_resume
    raise Exception(f"Upload failed: \nTraceback:\n{tb_str}")
Exception: Upload failed: 
Traceback:
Traceback (most recent call last):
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/src/linkedIn_easy_applier.py", line 200, in _create_and_upload_resume
    f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/manager_facade.py", line 81, in pdf_base64
    pdf_base64 = HTML_to_PDF(temp_html_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 25, in HTML_to_PDF
    driver = create_driver_selenium()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 18, in create_driver_selenium
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__
    service.path = DriverFinder.get_path(service, options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
    raise err
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
    result = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
    raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /Users/elliothayner/GitHub/linkedIn_AI_hawk/virtual/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug.
The chromedriver version cannot be discovered




^C%                                                                                                                                                                                                                                                                 
(virtual) elliothayner@Elliots-MacBook-Air linkedIn_AI_hawk % 
```

**Comment by spectreDeveloper** [comment]
Hi,
Is not possible is related to my code, because is not implemented actually

**Comment by cguisado** [comment]
Any updates here? I'm having the same issue

**Comment by max870701** [comment]
Solution

1. Find the file `/virtual/lib/python3.11/site-packages/lib_resume_builder_AIHawk/utils.py` in your virtual environment. directory.

2. Modify the `create_driver_selenium` function as below.
    ```python
    def create_driver_selenium():
        options = get_chrome_browser_options()
        service = ChromeService(executable_path=ChromeDriverManager().install())
        return webdriver.Chrome(service=service, options=options)
    ```

**Comment by feder-cr** [comment]
@max870701 please do a PR

**Comment by feder-cr** [comment]
@rahul-lohra @max870701 @RohanBera  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
