### ISSUE TITLE
Bot is viewing and not applying

### ISSUE THREAD

**Issue by NobelShaji** [feder-cr/Auto_Jobs_Applier_AIHawk#418]
I got the bot running and its just viewing the jobs and not creating a resume and not applying for any jobs. it keeps on going till the last step of easyapply and choose resume option, but in the next step its going to the next job

**Comment by Steadyx** [comment]
This right here and for me it's incredibly slow. Takes like 15 minutes for a single job, I have noticed an error that I will post as well as it might be related:

```
Traceback (most recent call last):
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 200, in _create_and_upload_resume
    f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/manager_facade.py", line 81, in pdf_base64
    pdf_base64 = HTML_to_PDF(temp_html_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 24, in HTML_to_PDF
    driver = create_driver_selenium()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 16, in create_driver_selenium
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__
    service.path = DriverFinder.get_path(service, options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
    raise err
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
    result = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
    raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug.
The chromedriver version cannot be discovered


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 61, in job_apply
    self._fill_application_form(job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 125, in _fill_application_form
    self.fill_up(job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 169, in fill_up
    self._process_form_element(element, job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 173, in _process_form_element
    self._handle_upload_fields(element, job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 190, in _handle_upload_fields
    self._create_and_upload_resume(element, job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 206, in _create_and_upload_resume
    raise Exception(f"Upload failed: \nTraceback:\n{tb_str}")
Exception: Upload failed:
Traceback:
Traceback (most recent call last):
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 200, in _create_and_upload_resume
    f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/manager_facade.py", line 81, in pdf_base64
    pdf_base64 = HTML_to_PDF(temp_html_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 24, in HTML_to_PDF
    driver = create_driver_selenium()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 16, in create_driver_selenium
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__
    service.path = DriverFinder.get_path(service, options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
    raise err
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
    result = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
    raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug.
The chromedriver version cannot be discovered



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_job_manager.py", line 126, in apply_jobs
    self.easy_applier_component.job_apply(job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 65, in job_apply
    raise Exception(f"Failed to apply to job! Original exception: \nTraceback:\n{tb_str}")
Exception: Failed to apply to job! Original exception:
Traceback:
Traceback (most recent call last):
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 200, in _create_and_upload_resume
    f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/manager_facade.py", line 81, in pdf_base64
    pdf_base64 = HTML_to_PDF(temp_html_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 24, in HTML_to_PDF
    driver = create_driver_selenium()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 16, in create_driver_selenium
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__
    service.path = DriverFinder.get_path(service, options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
    raise err
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
    result = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
    raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug.
The chromedriver version cannot be discovered


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 61, in job_apply
    self._fill_application_form(job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 125, in _fill_application_form
    self.fill_up(job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 169, in fill_up
    self._process_form_element(element, job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 173, in _process_form_element
    self._handle_upload_fields(element, job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 190, in _handle_upload_fields
    self._create_and_upload_resume(element, job)
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 206, in _create_and_upload_resume
    raise Exception(f"Upload failed: \nTraceback:\n{tb_str}")
Exception: Upload failed:
Traceback:
Traceback (most recent call last):
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/src/linkedIn_easy_applier.py", line 200, in _create_and_upload_resume
    f.write(base64.b64decode(self.resume_generator_manager.pdf_base64(job_description_text=job.description)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/manager_facade.py", line 81, in pdf_base64
    pdf_base64 = HTML_to_PDF(temp_html_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 24, in HTML_to_PDF
    driver = create_driver_selenium()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 16, in create_driver_selenium
    return webdriver.Chrome(service=service, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__
    service.path = DriverFinder.get_path(service, options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path
    raise err
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path
    path = shutil.which(service.path) or SeleniumManager().driver_location(options)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location
    result = self.run(args)
             ^^^^^^^^^^^^^^
  File "/Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run
    raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /Users/edwardkemp/projects/linkedIn_auto_jobs_applier_with_AI/virtual/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug.
The chromedriver version cannot be discovered
```

I should note that I have chromedriver and it is installed.

**Comment by X0nic** [comment]
Same problem for me too. Seems to be related to this commit: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/commit/d8b7e7fda6e390316b6d8d2f4bdb07c9b0cc4b1f

**Comment by fransanda** [comment]
> Same problem for me too. Seems to be related to this commit: [d8b7e7f](https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/commit/d8b7e7fda6e390316b6d8d2f4bdb07c9b0cc4b1f)

Soory for my ignorance. Why did you interpretaed was related to that? Di you tried those new files and it worked?

**Comment by X0nic** [comment]
No I havent been able to get it working. What I do know is that the failing code was added in that commit. It seems to be using a new method to generate the resume. It tries to start another instance of chrome to print a pdf and is unable to start chrome and then fails.

**Comment by X0nic** [comment]
I was able to get the previous commit (acc6b442518a8751bcb3611cd6320d8588ec836b) working.

**Comment by jcrandell7** [comment]
Same issue here. 

As suggested, I have ensured the chromedriver is the same as my chrome version. 

I've also ensured that my chromedriver is in my $PATH

I've tested a couple of simple scripts that leverage the chromedriver just to see if I can reproduce the error outside of this program.

```
# vim test.py
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

options = Options()
# options.add_argument('--headless')
# options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

driver.get("https://python.org")
print(driver.title)
time.sleep(10)
driver.close()
```

AND

```
import time
from selenium import webdriver

driver = webdriver.Chrome('/usr/local/sbin/chromedriver')  # Optional argument, if not specified will search path.
driver.get('http://www.google.com/');
time.sleep(5) # Let the user actually see something!
search_box = driver.find_element_by_name('q')
search_box.send_keys('ChromeDriver')
search_box.submit()
time.sleep(5) # Let the user actually see something!
driver.quit()
```

**Comment by fransanda** [comment]
> I was able to get the previous commit ([acc6b44](https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/commit/acc6b442518a8751bcb3611cd6320d8588ec836b)) working.

So it's fullly working now? It's applying for all jobs? Or now you have other errors?

**Comment by X0nic** [comment]
> So it's fullly working now? It's applying for all jobs? Or now you have other errors?

I wouldn't consider that working. I checked out an old version.

**Comment by X0nic** [comment]
Not sure what just happened, but the history has been removed. Might have issue if you trying and look for that commit now.

**Comment by moudimash99** [comment]
Yeah it's not working for me too, hasnt been working for a week now and at latest commit

**Comment by Steadyx** [comment]
It's working for me now on latest branch

**Comment by moudimash99** [comment]
The cause is this for me, will update and check if it is fixed
def extract_job_information_from_tile(self, job_tile):
        job_title, company, job_location, apply_method, link = "", "", "", "", ""
        try:
            job_title = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title').text
            link = job_tile.find_element(By.CLASS_NAME, 'job-card-list__title').get_attribute('href').split('?')[0]
            company = job_tile.find_element(By.CLASS_NAME, 'job-card-container__primary-description').text
        except:
            pass
        try:
            job_location = job_tile.find_element(By.CLASS_NAME, 'job-card-container__metadata-item').text
        except:
            pass
        try:
            apply_method = job_tile.find_element(By.CLASS_NAME, 'job-card-container__apply-method').text
        except:
            apply_method = "Applied"

        return job_title, company, job_location, link, apply_method

**Comment by moudimash99** [comment]
So I went back, download the code directly as a zip and ran it , still getting the same error. the error is that the job postings arent being parsed correctly for some reason. I will delve deeper into this and check out why "Apply method not found, assuming 'Applied'."
here are the logs for the first page which they all have the same error. I understand it's a bit janky, as even for me some days it works but Im not sure why. But I'm sure its from the function extract_job_information_from_tile
[test.txt](https://github.com/user-attachments/files/17175943/test.txt)

**Comment by fransanda** [comment]
> So I went back, download the code directly as a zip and ran it , still getting the same error. the error is that the job postings arent being parsed correctly for some reason. I will delve deeper into this and check out why "Apply method not found, assuming 'Applied'." here are the logs for the first page which they all have the same error. I understand it's a bit janky, as even for me some days it works but Im not sure why. But I'm sure its from the function extract_job_information_from_tile [test.txt](https://github.com/user-attachments/files/17175943/test.txt)

Im having the same issue. Please let me know if you find a solution.

**Comment by moudimash99** [comment]
for sure, can you send me your log file ? or at least something like this, so that I can see what your divs are

 Extracting job information from tile
<li id="ember393" class="ember-view   jobs-search-results__list-item occludable-update p0 relative scaffold-layout__list-item">


    <div class="job-card-job-posting-card-wrapper



        " data-job-id="4032943451" data-view-name="job-card">
      <a class="app-aware-link  job-card-job-posting-card-wrapper__card-link" href="https://www.linkedin.com/jobs/search?keywords=Developpeur%20de%20logiciels&amp;distance=100&amp;start=0&amp;f_TPR=r604800&amp;f_JT=F%2CC%2CP&amp;f_LF=f_AL&amp;origin=JOB_SEARCH_PAGE_OTHER_ENTRY&amp;currentJobId=4032943451&amp;trackingId=ffosMAFhrYF0C%2BrWWaXFaw%3D%3D&amp;refId=O4Qe2H%2FLjO%2BLMnNXAUcl8w%3D%3D&amp;eBP=CwEAAAGSOgnMHWIaP02Tjvw9hk1y9YOarPnY6JqEyuOTa52oWVeeY6f3dg8t8cWkjTxQZi4X1FCCd0NVnH-a5W2ktxaw1rPfWOcGHx5ih2zA-bVKwJwbJ8kfe6viw5IFirxDwMjeSYmibXXniMx8Wv_bgdxTfpWscqNXKgvy2qw9ZyLnZNElRU0m18VEAlClGO39WFjINYbZV5eBaEvYurZA7Fv2DogDt8CoHuyewJTo2tvCDRuX2Om3UMxR62rwa-o5aSy41MUFdE8PwCwvHNbwWJwe6cQawuJ8isY00Qtxev3QcaRehNgYlqn4pMdNdvs-XImMawuUPUiXXmVq1ftkLfi2OGdMNn48Zg6TdJGgPqjZxXrm0fdvHNyMc6q5qRegGr74_OIyoZM0DrFNBBGwodKtXVANpNe8JxnwWEdyO2OnuaxUnrEzU4o-437ZevRgbNLLSKU30djjAUNofK5r6WLivKN5&amp;location=France" data-test-app-aware-link="">
        <div class="job-card-job-posting-card-wrapper__entity-lockup
            ">
          <div id="ember394" class="artdeco-entity-lockup artdeco-entity-lockup--size-4 ember-view">
            <div id="ember395" class="artdeco-entity-lockup__image artdeco-entity-lockup__image--type-square ember-view" type="square">
                <div class="pr3">

    <div class="ivm-image-view-model   ">

    <div class="ivm-view-attr__img-wrapper

        ">

          <img width="56" src="https://media.licdn.com/dms/image/v2/C4D0BAQHAThlPYV88-g/company-logo_100_100/company-logo_100_100/0/1630544839888/acensi_nord_logo?e=1735776000&amp;v=beta&amp;t=5pExL63rLsOjfVTq7QXVvBts-TiTXHuM29arm49gTM4" loading="lazy" height="56" alt="ACENSI NORD logo" id="ember396" class="ivm-view-attr__img--centered EntityPhoto-square-4   evi-image lazy-image ember-view">
    </div>

          </div>

                </div>

</div>
            <div class="job-card-job-posting-card-wrapper__content
                ">
              <div class="flex-grow-1">
                <div id="ember397" class="artdeco-entity-lockup__title ember-view">
                  <span class="job-card-job-posting-card-wrapper__title
                      ">
                    <span aria-hidden="true"><strong>Développeur back-end/Développeuse back-end</strong></span><span class="visually-hidden">Développeur back-end/Développeuse back-end</span>
                  </span>

</div>
                <div id="ember398" class="artdeco-entity-lockup__subtitle ember-view">
                  <div>
                    ACENSI NORD
                  </div>
                </div>
                    <div id="ember399" class="artdeco-entity-lockup__caption ember-view">
                      <div>
                        Greater Lille Metropolitan Area (On-site)
                      </div>
                    </div>
                  <div id="ember400" class="artdeco-entity-lockup__metadata ember-view">


    <div class="job-card-job-posting-card-wrapper__job-insights">

    <div class="ivm-image-view-model   ">

    <div class="ivm-view-attr__img-wrapper

        ">

        <svg role="img" aria-hidden="false" aria-label="Response time is typically 4 days" class="ivm-view-attr__icon ivm-view-attr__icon--signal-positive  " xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" data-supported-dps="24x24" data-test-icon="responsive-medium">

    <use href="#responsive-medium" width="24" height="24"></use>
</svg>

    </div>

          </div>

        <div class="job-card-job-posting-card-wrapper__job-insight-text">
          Response time is typically 4 days
        </div>
    </div>

                  </div>
              </div>
              <div id="ember401" class="artdeco-entity-lockup__metadata ember-view">
                <ul class="job-card-job-posting-card-wrapper__footer-items">

                      <li class="job-card-job-posting-card-wrapper__footer-item">
                        Promoted
                      </li>

                        <li class="job-card-job-posting-card-wrapper__footer-item">
                          <svg role="none" aria-hidden="true" class="job-card-job-posting-card-wrapper__footer-item-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" data-supported-dps="16x16" data-test-icon="linkedin-bug-color-small">
    <svg display="var(--hue-web-svg-display-light)">
      <image href="https://static.licdn.com/aero-v1/sc/h/cukxdu7s8ldmqz13xdao5xe75" x="0" y="0" width="16" height="16"></image>
    </svg>
    <svg display="var(--hue-web-svg-display-dark)">
      <image href="https://static.licdn.com/aero-v1/sc/h/7qvn5nkkh1mlaqd5xm0radtjv" x="0" y="0" width="16" height="16"></image>
    </svg>
</svg>


                          Easy Apply
                        </li>
                </ul>
              </div>
            </div>

</div>
        </div>
      </a>
      <div class="job-card-job-posting-card-wrapper__actions
          pr1">


      <div>
          <button aria-label="Dismiss Développeur back-end/Développeuse back-end job" id="ember402" class="job-card-container__action job-card-container__action-small artdeco-button artdeco-button--muted artdeco-button--2 artdeco-button--tertiary ember-view" type="button">
<span class="artdeco-button__text">

            <svg role="none" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" data-supported-dps="16x16" data-test-icon="close-small">

    <use href="#close-small" width="16" height="16"></use>
</svg>

            <span class="job-card-container__action-text"></span>

</span></button>
      </div>


      </div>
    </div>


        </li>

**Comment by moudimash99** [comment]
@fransanda I fixed it for myself, created a pull request but not sure if it's the same problem for all. Try downloading if you want the code from [my pull request](https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/pull/449). If you want only download the file [aihawk_job_manager.py](https://github.com/moudimash99/Auto_Jobs_Applier_AIHawk/blob/main/src/aihawk_job_manager.py) and replace it, shouldn't need to change anything else if you're on the latest commit

**Comment by fransanda** [comment]
Mate! it worked! it is working so perfectly! I just had to replace the file "aihawk_job_manager.py" for yours! Im so greatful, thank you so much!

PS: do you know what was wrong? I still can not understand the issue.

**Comment by fransanda** [comment]
@moudimash99 Mate! it worked! it is working so perfectly! I just had to replace the file "aihawk_job_manager.py" for yours! Im so greatful, thank you so much!

PS: do you know what was wrong? I still can not understand the issue.

**Comment by moudimash99** [comment]
@fransanda its because we have certain html identifiers different than the current users. I'm unsure why that's the case though

**Comment by fransanda** [comment]
@moudimash99 for some reason now it stopped woring again. Again the same issue it's not finding the class names. Is it still working for you?

**Comment by feder-cr** [comment]
@X0nic @Steadyx @moudimash99 @jcrandell7 @fransanda @NobelShaji  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by AdrianoLusso** [comment]
@feder-cr have you find s solution for it? I having the same issue. Maybe i should talk to you in telegram?
