### ISSUE TITLE
[BUG]: <Provide a clear, descriptive title> Cannot generate resume: Chromedriver version not discovered

### ISSUE THREAD

**Issue by nitSubedi** [feder-cr/Auto_Jobs_Applier_AIHawk#453]
### Describe the bug

2024-09-30 11:27:11.553 | ERROR    | src.aihawk_easy_applier:_create_and_upload_resume:470 - Failed to generate resume: Message: Selenium Manager failed for: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug. The chromedriver version cannot be discovered  2024-09-30 11:27:11.556 | ERROR    | src.aihawk_easy_applier:_create_and_upload_resume:472 - Traceback: Traceback (most recent call last):   File "/Users/maauri/Projects/Auto_jobs/linkedIn_auto_jobs_applier_with_AI/src/aihawk_easy_applier.py", line 442, in _create_and_upload_resume     resume_pdf_base64 = self.resume_generator_manager.pdf_base64(job_description_text=job.description)                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lib_resume_builder_AIHawk/manager_facade.py", line 81, in pdf_base64     pdf_base64 = HTML_to_PDF(temp_html_path)                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 25, in HTML_to_PDF     driver = create_driver_selenium()              ^^^^^^^^^^^^^^^^^^^^^^^^   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py", line 18, in create_driver_selenium     return webdriver.Chrome(service=service, options=options)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 82, in __init__     service.path = DriverFinder.get_path(service, options)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 43, in get_path     raise err   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 40, in get_path     path = shutil.which(service.path) or SeleniumManager().driver_location(options)                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 91, in driver_location     result = self.run(args)              ^^^^^^^^^^^^^^   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 112, in run     raise SeleniumManagerException(f"Selenium Manager failed for: {command}.\n{result}{stderr}") selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug. The chromedriver version cannot be discovered   2024-09-30 11:27:11.556 | ERROR    | src.aihawk_easy_applier:fill_up:337 - Failed to find form elements: Message: Selenium Manager failed for: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/selenium/webdriver/common/macos/selenium-manager --browser chrome --output json --debug. The chromedriver version cannot be discovered

### Steps to reproduce

Run the program after cloning using python3 main.py

### Expected behavior

The resume should have been generated

### Actual behavior

Selects an already uploaded resume and proceeds

### Branch

main

### Python version

3.12.2

### LLM Used

OpenAI

### Model used

GPT-4o-mini

**Comment by craschnet** [comment]
Do you have the latest version of the chrome & chrome driver installed
https://googlechromelabs.github.io/chrome-for-testing/



if Windows:
And do you have your `$PATH` able to reach it?
if Linux:
Is chromedriver in `/usr/bin/` and is executable (`chown +x chromedriver`)

**Comment by nitSubedi** [comment]
my chrome is : 129.0.6668.71
homebrew says the chromedriver is the latest version
I am using a mac and cannot open the chrome-for-testing as it says its damaged

**Comment by Ritesh261** [comment]
To resolve the issue you’re facing, navigate to the file utils.py within your environment at the following path:
This was the path in my conda env: 

```
/opt/homebrew/Caskroom/miniforge/base/envs/hawk-env/lib/python3.12/site-packages/lib_resume_builder_AIHawk
```
You’ll see the following existing code for the create_driver_selenium function:
```
def create_driver_selenium():
    options = get_chrome_browser_options()  # Use the method to get Chrome options

    chrome_install = ChromeDriverManager().install()
    folder = os.path.dirname(chrome_install)
    chromedriver_path = os.path.join(folder, "chromedriver.exe")

    service = ChromeService(executable_path=chromedriver_path)
    return webdriver.Chrome(service=service, options=options)

**Comment by swingcake** [comment]
> To resolve the issue you’re facing, navigate to the file utils.py within your environment at the following path: This was the path in my conda env:
> 
> ```
> /opt/homebrew/Caskroom/miniforge/base/envs/hawk-env/lib/python3.12/site-packages/lib_resume_builder_AIHawk/utils.py
> ```
> 
> You’ll see the following existing code for the create_driver_selenium function:
> 
> ```
> def create_driver_selenium():
>     options = get_chrome_browser_options()  # Use the method to get Chrome options
> 
>     chrome_install = ChromeDriverManager().install()
>     folder = os.path.dirname(chrome_install)
>     chromedriver_path = os.path.join(folder, "chromedriver.exe")
> 
>     service = ChromeService(executable_path=chromedriver_path)
>     return webdriver.Chrome(service=service, options=options)
> ```
> 
> To address the issue, the path should be updated to match non-Windows environments (i.e., removing the .exe from the driver name). Here’s how you can modify the code:
> 
> ```
> def create_driver_selenium():
>     options = get_chrome_browser_options()  # Use the method to get Chrome options
> 
>     chrome_install = ChromeDriverManager().install()
>     folder = os.path.dirname(chrome_install)
>     if platform.system() == "Windows":
>         chromedriver_path = os.path.join(folder, "chromedriver.exe")
>     else:
>         chromedriver_path = os.path.join(folder, "chromedriver")
>     service = ChromeService(executable_path=chromedriver_path)
>     return webdriver.Chrome(service=service, options=options)
> ```
> 
> By updating the path to "chromedriver" and removing the .exe extension, this should resolve the issue you’re encountering in non-Windows environments.
> 
> This fix ensures that your script works consistently across systems where the ChromeDriver doesn’t use the .exe extension (like macOS or Linux). Let me know if you need further assistance!

Thanks for this! However, platform is not defined here which results in an error:
`if platform.system() == "Windows":`

I just completely removed the if block and just kept the else portion as that is enough to make it work on macOS.

**Comment by Axedyson** [comment]
@swingcake I think you need to import the platform package like this:

```Python
import os
import platform
import time
from selenium.common.exceptions import WebDriverException
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium import webdriver
import time
from webdriver_manager.chrome import ChromeDriverManager

def create_driver_selenium():
    options = get_chrome_browser_options()  # Use the method to get Chrome options

    chrome_install = ChromeDriverManager().install()
    folder = os.path.dirname(chrome_install)
    if platform.system() == "Windows":
        chromedriver_path = os.path.join(folder, "chromedriver.exe")
    else:
        chromedriver_path = os.path.join(folder, "chromedriver")
    service = ChromeService(executable_path=chromedriver_path)
    return webdriver.Chrome(service=service, options=options)
```

**Comment by swingcake** [comment]
@Axedyson didn't know it was a package, thx. I just removed that part anyway as I mentioned in my earlier comment so it works for me. Thanks for your reply! :)

**Comment by nitSubedi** [comment]
still cannot get it to work;  Runtime error: Failed to initialize browser, Selenium manager failure, chromedriver version cannot be discovered. 
It is only for this project, I have another project using selenium on my computer and it runs fine.

**Comment by feder-cr** [comment]
@Axedyson @swingcake @Ritesh261 @a-curious-coder @craschnet @nitSubedi @MuilaerteJunior @mmcc007 join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
